"""Mermaid flowchart (M10) for docs, wikis and Lucid's diagram-as-code panel. Byte-identical to tools/render_flow.py."""
import html

from ir_core.graph import live

from .layout import AUTO, VARIANT_TITLE, control, edge_list, label, lane_name, layout

CLASS_DEFS = [
    "  classDef auto fill:#DAE8FC,stroke:#6C8EBF,color:#1F2D3D",
    "  classDef review fill:#FFE6CC,stroke:#D79B00,stroke-width:3px,color:#3D2A00",
    "  classDef human fill:#FFFFFF,stroke:#4D4D4D,stroke-width:2px,color:#1A1A1A",
    "  classDef approval fill:#F8CECC,stroke:#B85450,stroke-width:3px,color:#3D0F0E",
    "  classDef unset fill:#FFFFFF,stroke:#999999,stroke-dasharray:4 3,color:#333333",
    "  classDef decision fill:#FFF2CC,stroke:#D6B656,color:#3D3000",
    "  classDef wait fill:#F5F5F5,stroke:#999999,stroke-dasharray:4 3,color:#333333",
    "  classDef queue fill:#FFE6CC,stroke:#D79B00,stroke-dasharray:4 3,color:#3D2A00",
    "  classDef terminal fill:#D5E8D4,stroke:#82B366,color:#1E3D1D",
]
CLASS_OF = {"automated": "auto", "hitl_review": "review", "human_task": "human", "approval": "approval",
            "unset": "unset", "decision": "decision", "wait": "wait", "event": "wait", "start": "terminal",
            "end": "terminal"}


def _quoted(s: str) -> str:
    return s.replace('"', "#quot;")


def _plain(s: str) -> str:
    """draw.io HTML label → Mermaid text (same transformation order as the reference)."""
    s = html.unescape(s).replace("<br>", "<br/>")
    for tag in ("<b>", "</b>", "<i>", "</i>"):
        s = s.replace(tag, "")
    return s.replace("~", "about ")


def _subgraph_id(lane: str) -> str:
    return lane.replace("act_", "lane_") if lane != AUTO else AUTO


def render_mermaid(ir: dict) -> str:
    lay = layout(ir)
    nodes = live(ir, "nodes")
    p = ir["process"]
    out = [f"%% {p['name']} — {VARIANT_TITLE.get(p.get('variant'), '')} process flow (IR v{p['version']}). "
           "Generated by Requirements Studio M10; do not edit.",
           "%% Legend: [AUTO] automated · [AUTO + HUMAN REVIEW] reviewed by a named person · [HUMAN] person does it ·",
           "%% APPROVAL GATE hexagon (rejected path in red) · HUMAN QUEUE exceptions handed to a person · "
           "dashed = exception/SLA route",
           "flowchart LR"]
    for ln in lay["order"]:
        out.append(f'  subgraph {_subgraph_id(ln)}["{_quoted(lane_name(ir, ln))}"]')
        out.append("    direction LR")
        for k in sorted((k for k in nodes if lay["lanes"][k] == ln), key=lambda k: (lay["col"][k], k)):
            text = _quoted(_plain(label(ir, k)))
            kind = "approval" if control(ir, k) == "approval" else nodes[k]["type"]
            shape = {"start": f'(("{text}"))', "end": f'((("{text}")))', "decision": f'{{"{text}"}}',
                     "approval": f'{{{{"{text}"}}}}', "wait": f'(["{text}"])', "event": f'(("{text}"))'
                     }.get(kind, f'["{text}"]')
            out.append(f"    {k}{shape}")
        for q in (q for q in lay["queues"] if q["lane"] == ln):
            name = _quoted(ir["exceptions"][q["exception"]]["name"])
            out.append(f'    {q["id"]}["HUMAN QUEUE<br/>{name}<br/>{_quoted(lane_name(ir, ln))}"]')
        out.append("  end")

    edges = edge_list(ir)
    rejected = []
    for i, (_eid, s, t, text, kind) in enumerate(edges):
        arrow = "-->" if kind in ("flow", "reject") else "-.->"
        out.append(f"  {s} {arrow}" + (f'|"{_quoted(text)}"|' if text else "") + f" {t}")
        if kind == "reject":
            rejected.append(i)
    queue_links = []
    for j, q in enumerate(lay["queues"]):
        out.append(f'  {q["src"]} -.->|"Exception"| {q["id"]}')
        queue_links.append(len(edges) + j)

    out += CLASS_DEFS
    for ln in lay["order"]:
        out.append(f"  style {_subgraph_id(ln)} fill:#FAFAFA,stroke:#C8C8C8,color:#333333")
    groups: dict[str, list[str]] = {}
    for k in sorted(nodes):
        groups.setdefault(CLASS_OF[control(ir, k)], []).append(k)
    if lay["queues"]:
        groups["queue"] = [q["id"] for q in lay["queues"]]
    for cls in sorted(groups):
        out.append(f"  class {','.join(groups[cls])} {cls}")
    if rejected:
        out.append(f"  linkStyle {','.join(map(str, rejected))} stroke:#B85450,color:#B85450")
    if queue_links:
        out.append(f"  linkStyle {','.join(map(str, queue_links))} stroke:#D79B00")
    return "\n".join(out) + "\n"
