"""Azure Boards CSV import (M9): ID empty (new items), the Feature in 'Title 1', each story in 'Title 2' below it.

Byte-identical to tools/render_exports.py::ado_csv for the Agile process. RS_ADO_PROCESS=scrum names the stories
'Product Backlog Item'. A draft adds a DRAFT tag. Azure Boards imports at most 1,000 rows at a time.
"""
import html

from .common import change_line, control_label, gwt_lines, human_line, slug, story_text, to_csv

PRIORITY = {"must": 1, "should": 2, "could": 3, "wont": 4, None: 2}
STORY_TYPE = {"agile": "User Story", "scrum": "Product Backlog Item"}
MAX_ROWS = 1000
e = html.escape


def description(ir: dict, sid: str, s: dict) -> str:
    parts = [f"<p><b>Story:</b> {e(story_text(ir, s))}</p>",
             f"<p><b>Control:</b> {e(human_line(ir, s))}<br><b>Change from today:</b> {e(change_line(s))}</p>"]
    if s["edge_cases"]:
        parts.append("<p><b>Edge cases and exceptions</b></p><ul>"
                     + "".join(f"<li>{e(x['title'])}: {e(x['handling'])}</li>" for x in s["edge_cases"]) + "</ul>")
    if s["data_requirements"]:
        parts.append("<p><b>Data</b></p><ul>" + "".join(
            f"<li>{e(ir['entities'][d['entity_id']]['name'])} ({d['access'].replace('_', '/')}): "
            f"{e(', '.join(d['attributes']))}</li>" for d in s["data_requirements"]) + "</ul>")
    if s["nfr_ids"]:
        parts.append("<p><b>Non-functional</b></p><ul>" + "".join(
            f"<li>[{ir['nfrs'][n]['category']}] {e(ir['nfrs'][n]['statement'])}</li>" for n in s["nfr_ids"]) + "</ul>")
    if s["open_questions"]:
        parts.append("<p><b>Open questions</b></p><ul>"
                     + "".join(f"<li>{e(q['text'])}</li>" for q in s["open_questions"]) + "</ul>")
    parts.append(f"<p><i>Generated by Requirements Studio from {ir['process']['id']} "
                 f"v{ir['process']['version']} ({sid}).</i></p>")
    return "".join(parts)


def acceptance(ir: dict, s: dict) -> str:
    out = []
    for i, aid in enumerate(s["ac_ids"], 1):
        ac = ir["acceptance_criteria"][aid]
        out.append(f"<p><b>AC{i} – {e(ac['title'])}</b> ({ac.get('kind', 'happy_path').replace('_', ' ')})</p><ul>"
                   + "".join(f"<li><b>{kw}</b> {e(line)}</li>" for kw, line in gwt_lines(ac)) + "</ul>")
    return "".join(out)


def ado_csv(ir: dict, stories: dict, idea_title: str, idea_summary: str, *, process: str = "agile",
            draft: bool = False) -> str:
    if process not in STORY_TYPE:
        raise ValueError(f"RS_ADO_PROCESS must be one of {sorted(STORY_TYPE)}")
    if len(stories) + 1 > MAX_ROWS:
        raise ValueError(f"Azure Boards imports at most {MAX_ROWS} rows; this idea has {len(stories) + 1}")
    tag = slug(ir["process"]["id"])
    draft_tag = "; DRAFT" if draft else ""
    rows = [["", "Feature", idea_title, "", f"<p>{e(idea_summary)}</p>", "", 2,
             f"requirements-studio; {tag}{draft_tag}"]]
    for sid, s in stories.items():
        rows.append(["", STORY_TYPE[process], "", s["title"], description(ir, sid, s), acceptance(ir, s),
                     PRIORITY[s["priority"]], f"requirements-studio; {tag}; {control_label(s)}{draft_tag}"])
    return to_csv(rows, ["ID", "Work Item Type", "Title 1", "Title 2", "Description", "Acceptance Criteria", "Priority",
                         "Tags"])
