"""Improvements report (M11 Outputs, M9 exports/improvements.md). Port of tools/render_exports.py::improvements_md;
byte-identical to samples/client_kyc/exports/improvements.md (tested)."""


def _or_dash(value) -> str:
    return "—" if value is None else str(value)


def improvements_md(as_is: dict, to_be: dict, suggestions: list[dict], *, draft_banner: str | None = None) -> str:
    accepted = [x for x in suggestions if x["status"] == "accepted"]
    rejected = [x for x in suggestions if x["status"] == "rejected"]
    hours = round(sum(x["benefit"].get("hours_saved_per_month") or 0 for x in accepted), 1)
    today = sum(n.get("as_is_effort", {}).get("minutes_per_case") or 0 for n in as_is["nodes"].values())
    a, t = as_is["process"], to_be["process"]
    lines = [f"# Improvements: {a['name']}", "",
             f"_As-is {a['id']} v{a['version']} → to-be {t['id']} v{t['version']}. "
             "Generated by Requirements Studio (M11); do not edit._", "",
             *([draft_banner, ""] if draft_banner else []),
             f"**{len(accepted)} accepted, {len(rejected)} rejected.** Manual effort captured today: ~{today:g} "
             f"minutes per client. Accepted suggestions remove about **{hours:g} analyst hours a month** at current "
             "volume, before time spent on the human reviews that remain.", "",
             "| ID | Suggestion | Decision | Saves (min per case) | Hours per month | Human control kept or added |",
             "|---|---|---|---|---|---|"]
    for x in suggestions:
        b = x["benefit"]
        lines.append(f"| {x['suggestion_id']} | {x['title']} | {x['status']} | "
                     f"{_or_dash(b.get('minutes_saved_per_case'))} | {_or_dash(b.get('hours_saved_per_month'))} | "
                     f"{x['controls']} |")
    lines.append("")
    for x in suggestions:
        lines += [f"## {x['suggestion_id']} — {x['title']} ({x['status']})", "", x["change_summary"], "",
                  f"**Why:** {x['rationale']}"]
        if x["evidence"]:
            lines += [""] + [f"> \"{e['excerpt']}\" — {e['locator']}" for e in x["evidence"]]
        lines += ["", f"**Human control:** {x['controls']}"]
        if x.get("risk"):
            lines.append(f"**Risk:** {x['risk']}")
        if x["benefit"].get("qualitative"):
            lines.append(f"**Benefit:** {x['benefit']['qualitative']}")
        if (x.get("decision") or {}).get("reason"):
            lines.append(f"**Decision reason:** {x['decision']['reason']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"
