"""Jira Cloud CSV import (M9): the Epic first (Issue ID 1), then every Story with Parent = 1.

In the importer, map Issue ID → Issue ID and Parent → Parent so stories link to the epic. Byte-identical to
tools/render_exports.py::jira_csv for ready ideas; a draft adds a DRAFT label (fourth Labels column).
"""
from ir_core.graph import closure

from .common import change_line, control_label, gwt_lines, human_line, slug, story_text, to_csv

PRIORITY = {"must": "High", "should": "Medium", "could": "Low", "wont": "Lowest", None: "Medium"}


def _rule_text(rule: dict) -> str:
    logic = rule["logic"]
    if logic["kind"] != "table":
        return logic.get("expression") or logic.get("text")
    parts = []
    for row in logic["rows"]:
        conds = [f"{c.split('.')[1]}={w}" for c, w in zip(logic["columns"], row["when"], strict=False) if w != "*"]
        parts.append(f"{' & '.join(conds)} → {row['then']}" if conds else f"otherwise → {row['then']}")
    return "; ".join(parts)


def description(ir: dict, sid: str, s: dict) -> str:
    """Jira wiki markup."""
    lines = [f"*Story:* {story_text(ir, s)}", "",
             f"*Priority:* {s['priority'] or 'not set'} · *Control:* {human_line(ir, s)}",
             f"*Change from today:* {change_line(s)}", "", "h3. Acceptance criteria"]
    for i, aid in enumerate(s["ac_ids"], 1):
        ac = ir["acceptance_criteria"][aid]
        lines.append(f"*AC{i} – {ac['title']}* ({ac.get('kind', 'happy_path').replace('_', ' ')})")
        lines += [f"* *{kw}* {line}" for kw, line in gwt_lines(ac)]
    if s["edge_cases"]:
        lines += ["", "h3. Edge cases and exceptions"] + [f"* {e['title']}: {e['handling']}" for e in s["edge_cases"]]
    rules = sorted(i for i in closure(ir, s["node_ids"]) if i.startswith("rule_"))
    if rules:
        lines += ["", "h3. Business rules"]
        lines += [f"* {ir['decision_rules'][r]['name']}: {_rule_text(ir['decision_rules'][r])}" for r in rules]
    if s["data_requirements"]:
        lines += ["", "h3. Data"]
        for d in s["data_requirements"]:
            name, access = ir["entities"][d["entity_id"]]["name"], d["access"].replace("_", "/")
            lines.append(f"* {name} ({access}): {', '.join(d['attributes'])}")
    if s["nfr_ids"]:
        lines += ["", "h3. Non-functional"] + [f"* [{ir['nfrs'][n]['category']}] {ir['nfrs'][n]['statement']}"
                                               for n in s["nfr_ids"]]
    if s["open_questions"]:
        lines += ["", "h3. Open questions"] + [f"* {q['text']} (waiting on {q['asked_to'] or 'owner'})"
                                               for q in s["open_questions"]]
    lines += ["", f"_Generated by Requirements Studio from {ir['process']['id']} v{ir['process']['version']} ({sid})._"]
    return "\n".join(lines)


def jira_csv(ir: dict, stories: dict, idea_title: str, idea_summary: str, *, draft: bool = False) -> str:
    tag = slug(ir["process"]["id"])
    p = ir["process"]
    extra = ["DRAFT"] if draft else []
    rows = [["1", "Epic", idea_title, "", "Medium", "requirements-studio", tag, "", *extra,
             f"{idea_summary}\n\nProcess flow: to_be_process_flow.drawio (import into Lucidchart).\n"
             f"_Generated by Requirements Studio from {p['id']} v{p['version']}._"]]
    for i, (sid, s) in enumerate(stories.items(), 2):
        rows.append([str(i), "Story", s["title"], "1", PRIORITY[s["priority"]], "requirements-studio", tag,
                     control_label(s), *extra, description(ir, sid, s)])
    header = ["Issue ID", "Issue Type", "Summary", "Parent", "Priority", "Labels", "Labels", "Labels",
              *(["Labels"] if draft else []), "Description"]
    return to_csv(rows, header)
