#!/usr/bin/env python3
"""Reference export renderers (M9): Jira CSV, Azure DevOps CSV, backlog CSV + Excel, improvements report.

Deterministic for the text formats (byte-identical on the same input). The .xlsx is checked by cell values.
Usage: python tools/render_exports.py <to_be_ir.json> <out_dir> [as_is_ir.json suggestions.json]
"""
from __future__ import annotations

import csv
import html
import io
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rs_reference as R  # noqa: E402
import render_flow as RF  # noqa: E402

JIRA_PRIORITY = {"must": "High", "should": "Medium", "could": "Low", "wont": "Lowest", None: "Medium"}
ADO_PRIORITY = {"must": 1, "should": 2, "could": 3, "wont": 4, None: 2}
MODE = {"automated": "Automated", "hitl_review": "Automated + human review", "human_task": "Human task", "approval": "Approval gate", None: "Not set"}


def _actor(ir, a):
    return ir["actors"][a]["name"] if a and a in ir["actors"] else "—"


def _article(w):
    return "an" if w[:1].upper() in "AEIOU" else "a"


def _slug(s):
    return s.lower().replace("proc_", "").replace("_", "-")


def _csv(rows, header):
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n", quoting=csv.QUOTE_MINIMAL)
    w.writerow(header)
    w.writerows(rows)
    return buf.getvalue()


def _gwt_lines(ac):
    out = []
    for kw, key in (("Given", "given"), ("When", "when"), ("Then", "then")):
        for i, line in enumerate(ac[key]):
            out.append((kw if i == 0 else "And", line))
    return out


def _human_line(ir, s):
    hc = s["human_control"]
    t = MODE[hc["mode"]]
    if hc.get("actor_id"):
        t += f" — {'approver' if hc['mode'] == 'approval' else 'reviewer'}: {_actor(ir, hc['actor_id'])}"
    if hc.get("trigger"):
        t += f" ({hc['trigger'].replace('_', ' ')})"
    if hc.get("criteria"):
        t += f". Checks: {hc['criteria']}"
    for q in hc["queues"]:
        t += f". Exception '{ir['exceptions'][q['exception_id']]['name']}' goes to {_actor(ir, q['actor_id'])}"
    return t


def _change_line(s):
    ch = s.get("change")
    if not ch:
        return "Unchanged from today"
    was = {"human_task": "manual", "approval": "an approval", "hitl_review": "reviewed"}.get(ch.get("was"), ch.get("was") or "")
    t = f"{ch['kind'].replace('_', ' ').capitalize()} by suggestion {ch['suggestion_id']}"
    if was:
        t += f" (today: {was}"
        t += f", ~{ch['minutes_saved_per_case']:g} min per case)" if ch.get("minutes_saved_per_case") is not None else ")"
    return t


def _story_text(ir, s):
    a = _actor(ir, s["as_a"])
    return f"As {_article(a)} {a}, I want to {s['i_want']}, so that {s['so_that']}."


# ------------------------------------------------------------------------------------------- Jira
def jira_description(ir, sid, s):
    L = [f"*Story:* {_story_text(ir, s)}", "", f"*Priority:* {s['priority'] or 'not set'} · *Control:* {_human_line(ir, s)}",
         f"*Change from today:* {_change_line(s)}", "", "h3. Acceptance criteria"]
    for i, aid in enumerate(s["ac_ids"], 1):
        ac = ir["acceptance_criteria"][aid]
        L.append(f"*AC{i} – {ac['title']}* ({ac.get('kind', 'happy_path').replace('_', ' ')})")
        L += [f"* *{kw}* {line}" for kw, line in _gwt_lines(ac)]
    if s["edge_cases"]:
        L += ["", "h3. Edge cases and exceptions"] + [f"* {e['title']}: {e['handling']}" for e in s["edge_cases"]]
    rules = sorted(i for i in R.closure(ir, s["node_ids"]) if i.startswith("rule_"))
    if rules:
        L += ["", "h3. Business rules"]
        for r in rules:
            lg = ir["decision_rules"][r]["logic"]
            L.append(f"* {ir['decision_rules'][r]['name']}: " + (
                "; ".join(" & ".join(f"{c.split('.')[1]}={w}" for c, w in zip(lg['columns'], row['when']) if w != '*') + f" → {row['then']}"
                          if any(w != "*" for w in row["when"]) else f"otherwise → {row['then']}" for row in lg["rows"])
                if lg["kind"] == "table" else lg.get("expression") or lg.get("text")))
    if s["data_requirements"]:
        L += ["", "h3. Data"] + [f"* {ir['entities'][d['entity_id']]['name']} ({d['access'].replace('_', '/')}): {', '.join(d['attributes'])}"
                                 for d in s["data_requirements"]]
    if s["nfr_ids"]:
        L += ["", "h3. Non-functional"] + [f"* [{ir['nfrs'][n]['category']}] {ir['nfrs'][n]['statement']}" for n in s["nfr_ids"]]
    if s["open_questions"]:
        L += ["", "h3. Open questions"] + [f"* {q['text']} (waiting on {q['asked_to'] or 'owner'})" for q in s["open_questions"]]
    L += ["", f"_Generated by Requirements Studio from {ir['process']['id']} v{ir['process']['version']} ({sid})._"]
    return "\n".join(L)


def jira_csv(ir, stories, idea_title, idea_summary) -> str:
    """Jira Cloud CSV import: epic first, stories after; map Issue ID → Issue ID and Parent → Parent in the importer."""
    tag = _slug(ir["process"]["id"])
    rows = [["1", "Epic", idea_title, "", "Medium", "requirements-studio", tag, "",
             f"{idea_summary}\n\nProcess flow: to_be_process_flow.drawio (import into Lucidchart).\n"
             f"_Generated by Requirements Studio from {ir['process']['id']} v{ir['process']['version']}._"]]
    for i, (sid, s) in enumerate(stories.items(), 2):
        rows.append([str(i), "Story", s["title"], "1", JIRA_PRIORITY[s["priority"]], "requirements-studio", tag,
                     f"control-{(s['human_control']['mode'] or 'unset').replace('_', '-')}", jira_description(ir, sid, s)])
    return _csv(rows, ["Issue ID", "Issue Type", "Summary", "Parent", "Priority", "Labels", "Labels", "Labels", "Description"])


# --------------------------------------------------------------------------------------- Azure DevOps
def ado_description(ir, sid, s):
    p = [f"<p><b>Story:</b> {html.escape(_story_text(ir, s))}</p>",
         f"<p><b>Control:</b> {html.escape(_human_line(ir, s))}<br><b>Change from today:</b> {html.escape(_change_line(s))}</p>"]
    if s["edge_cases"]:
        p.append("<p><b>Edge cases and exceptions</b></p><ul>" + "".join(f"<li>{html.escape(e['title'])}: {html.escape(e['handling'])}</li>" for e in s["edge_cases"]) + "</ul>")
    if s["data_requirements"]:
        p.append("<p><b>Data</b></p><ul>" + "".join(
            f"<li>{html.escape(ir['entities'][d['entity_id']]['name'])} ({d['access'].replace('_', '/')}): {html.escape(', '.join(d['attributes']))}</li>"
            for d in s["data_requirements"]) + "</ul>")
    if s["nfr_ids"]:
        p.append("<p><b>Non-functional</b></p><ul>" + "".join(f"<li>[{ir['nfrs'][n]['category']}] {html.escape(ir['nfrs'][n]['statement'])}</li>" for n in s["nfr_ids"]) + "</ul>")
    if s["open_questions"]:
        p.append("<p><b>Open questions</b></p><ul>" + "".join(f"<li>{html.escape(q['text'])}</li>" for q in s["open_questions"]) + "</ul>")
    p.append(f"<p><i>Generated by Requirements Studio from {ir['process']['id']} v{ir['process']['version']} ({sid}).</i></p>")
    return "".join(p)


def ado_acceptance(ir, s):
    out = []
    for i, aid in enumerate(s["ac_ids"], 1):
        ac = ir["acceptance_criteria"][aid]
        out.append(f"<p><b>AC{i} – {html.escape(ac['title'])}</b> ({ac.get('kind', 'happy_path').replace('_', ' ')})</p><ul>"
                   + "".join(f"<li><b>{kw}</b> {html.escape(line)}</li>" for kw, line in _gwt_lines(ac)) + "</ul>")
    return "".join(out)


def ado_csv(ir, stories, idea_title, idea_summary) -> str:
    """Azure Boards CSV import (Agile process): Feature in 'Title 1', its User Stories in 'Title 2', ID left empty."""
    tag = _slug(ir["process"]["id"])
    rows = [["", "Feature", idea_title, "", f"<p>{html.escape(idea_summary)}</p>", "", 2, f"requirements-studio; {tag}"]]
    for sid, s in stories.items():
        rows.append(["", "User Story", "", s["title"], ado_description(ir, sid, s), ado_acceptance(ir, s), ADO_PRIORITY[s["priority"]],
                     f"requirements-studio; {tag}; control-{(s['human_control']['mode'] or 'unset').replace('_', '-')}"])
    return _csv(rows, ["ID", "Work Item Type", "Title 1", "Title 2", "Description", "Acceptance Criteria", "Priority", "Tags"])


# ------------------------------------------------------------------------------------- Backlog CSV/XLSX
BACKLOG_HEADER = ["Story ID", "Title", "Priority", "Control", "As a", "I want", "So that", "Acceptance criteria", "Edge cases",
                  "Non-functional", "Upstream", "Downstream", "Systems", "Open questions", "Change from today", "DoR", "Confidence"]


def backlog_rows(ir, stories):
    rows = []
    for sid, s in stories.items():
        acs = []
        for i, aid in enumerate(s["ac_ids"], 1):
            ac = ir["acceptance_criteria"][aid]
            acs.append(f"AC{i} {ac['title']}: " + " ".join(f"{kw} {line}." for kw, line in _gwt_lines(ac)))
        dep = s["dependencies"]
        rows.append([sid, s["title"], s["priority"] or "", MODE[s["human_control"]["mode"]], _actor(ir, s["as_a"]),
                     f"to {s['i_want']}", s["so_that"], "\n".join(acs), "\n".join(e["title"] for e in s["edge_cases"]),
                     "\n".join(ir["nfrs"][n]["statement"] for n in s["nfr_ids"]), ", ".join(dep["upstream_story_ids"]),
                     ", ".join(dep["downstream_story_ids"]), ", ".join(_actor(ir, a) for a in dep["system_actor_ids"]),
                     "\n".join(q["text"] for q in s["open_questions"]), _change_line(s), s["dor_status"], s["confidence"]])
    return rows


def backlog_csv(ir, stories) -> str:
    return _csv(backlog_rows(ir, stories), BACKLOG_HEADER)


def ac_rows(ir, stories):
    rows = []
    for sid, s in stories.items():
        for aid in s["ac_ids"]:
            ac = ir["acceptance_criteria"][aid]
            rows.append([sid, aid, ac.get("kind", "happy_path"), ac["title"], "\n".join(ac["given"]), "\n".join(ac["when"]), "\n".join(ac["then"])])
    return rows


def compare_rows(as_is, to_be):
    rows = []
    for k, n in sorted(to_be["nodes"].items(), key=lambda kv: (R.bfs_distance(to_be).get(kv[0], 10**6), kv[0])):
        if n["type"] != "task":
            continue
        a = (as_is or {}).get("nodes", {}).get(k)
        rows.append([n["name"], MODE[(a or {}).get("hitl", {}).get("mode")] if a else "New step",
                     n.get("as_is_effort", {}).get("minutes_per_case", ""), MODE[n.get("hitl", {}).get("mode")],
                     (f"{n['change']['suggestion_id']}: {n['change']['kind'].replace('_', ' ')}" if n.get("change") else "Unchanged")])
    return rows


def suggestion_rows(suggestions):
    return [[x["suggestion_id"], x["title"], x["kind"].replace("_", " "), x["status"], x["benefit"].get("minutes_saved_per_case"),
             x["benefit"].get("hours_saved_per_month"), x["controls"], (x.get("decision") or {}).get("reason", "")] for x in suggestions]


SHEETS = {
    "Stories": BACKLOG_HEADER,
    "Acceptance criteria": ["Story ID", "AC ID", "Kind", "Title", "Given", "When", "Then"],
    "Human controls": ["Step", "Control", "Who", "When", "Checks"],
    "Improvements": ["ID", "Suggestion", "Kind", "Decision", "Minutes saved per case", "Hours saved per month", "Human control", "Reason"],
    "As-is vs to-be": ["Step", "Today", "Minutes per case today", "To-be", "Change"],
}


def workbook_rows(to_be, stories, as_is=None, suggestions=()):
    hs = [[r["step"], r["control"].replace("_", " "), r["who"] or "", r["when"].replace("_", " "), r["criteria"] or ""] for r in RF.hitl_summary(to_be)]
    return {"Stories": backlog_rows(to_be, stories), "Acceptance criteria": ac_rows(to_be, stories), "Human controls": hs,
            "Improvements": suggestion_rows(suggestions), "As-is vs to-be": compare_rows(as_is, to_be)}


def backlog_xlsx(path, to_be, stories, as_is=None, suggestions=()):
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter
    wb = Workbook()
    wb.remove(wb.active)
    data = workbook_rows(to_be, stories, as_is, suggestions)
    for name, header in SHEETS.items():
        ws = wb.create_sheet(name)
        ws.append(header)
        for c in ws[1]:
            c.font = Font(bold=True, color="FFFFFF"); c.fill = PatternFill("solid", fgColor="2F4858")
        for row in data[name]:
            ws.append(row)
        for col in range(1, len(header) + 1):
            ws.column_dimensions[get_column_letter(col)].width = 18 if len(header) > 8 else 28
            for cell in ws.iter_cols(min_col=col, max_col=col, min_row=2):
                for c in cell:
                    c.alignment = Alignment(wrap_text=True, vertical="top")
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions
    wb.properties.creator = "Requirements Studio"
    wb.save(path)


# ------------------------------------------------------------------------------------- Improvements
def improvements_md(as_is, to_be, suggestions) -> str:
    acc = [x for x in suggestions if x["status"] == "accepted"]
    rej = [x for x in suggestions if x["status"] == "rejected"]
    hours = round(sum(x["benefit"].get("hours_saved_per_month") or 0 for x in acc), 1)
    today = sum(n.get("as_is_effort", {}).get("minutes_per_case") or 0 for n in as_is["nodes"].values())
    L = [f"# Improvements: {as_is['process']['name']}", "",
         f"_As-is {as_is['process']['id']} v{as_is['process']['version']} → to-be {to_be['process']['id']} v{to_be['process']['version']}. "
         "Generated by Requirements Studio (M11); do not edit._", "",
         f"**{len(acc)} accepted, {len(rej)} rejected.** Manual effort captured today: ~{today:g} minutes per client. "
         f"Accepted suggestions remove about **{hours:g} analyst hours a month** at current volume, before time spent on the human reviews that remain.", "",
         "| ID | Suggestion | Decision | Saves (min per case) | Hours per month | Human control kept or added |", "|---|---|---|---|---|---|"]
    for x in suggestions:
        b = x["benefit"]
        L.append(f"| {x['suggestion_id']} | {x['title']} | {x['status']} | {b.get('minutes_saved_per_case') if b.get('minutes_saved_per_case') is not None else '—'} | "
                 f"{b.get('hours_saved_per_month') if b.get('hours_saved_per_month') is not None else '—'} | {x['controls']} |")
    L.append("")
    for x in suggestions:
        L += [f"## {x['suggestion_id']} — {x['title']} ({x['status']})", "", x["change_summary"], "", f"**Why:** {x['rationale']}"]
        if x["evidence"]:
            L += [""] + [f"> \"{e['excerpt']}\" — {e['locator']}" for e in x["evidence"]]
        L += ["", f"**Human control:** {x['controls']}"]
        if x.get("risk"):
            L.append(f"**Risk:** {x['risk']}")
        if x["benefit"].get("qualitative"):
            L.append(f"**Benefit:** {x['benefit']['qualitative']}")
        if x.get("decision", {}) and x["decision"].get("reason"):
            L.append(f"**Decision reason:** {x['decision']['reason']}")
        L.append("")
    return "\n".join(L).rstrip() + "\n"


def main():
    to_be = json.loads(Path(sys.argv[1]).read_text())
    out = Path(sys.argv[2]); out.mkdir(parents=True, exist_ok=True)
    as_is = json.loads(Path(sys.argv[3]).read_text()) if len(sys.argv) > 3 else None
    sugg = json.loads(Path(sys.argv[4]).read_text()) if len(sys.argv) > 4 else []
    st, title = to_be["stories"], to_be["process"]["name"]
    desc = to_be["process"].get("description", "")
    (out / "jira_import.csv").write_text(jira_csv(to_be, st, title, desc))
    (out / "azure_devops_import.csv").write_text(ado_csv(to_be, st, title, desc))
    (out / "stories_backlog.csv").write_text(backlog_csv(to_be, st))
    backlog_xlsx(out / "stories_backlog.xlsx", to_be, st, as_is, sugg)
    if as_is:
        (out / "improvements.md").write_text(improvements_md(as_is, to_be, sugg))
    print(f"wrote exports to {out}")


if __name__ == "__main__":
    main()
